### ISSUE TITLE
line drawing on paragraph breaks in long generations

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/love-and-ai#12]

**Comment by russellgoldenberg** [comment]
I feel like most of these look good to me. Any specific places it doesn't work?

**Comment by jadiehm** [comment]
In the "Around a week before I was due to arrive he..." wheel. The lines return to the center for paragraph breaks and retrace themselves.

<img width="676" alt="Screen Shot 2021-02-25 at 10 39 38 AM" src="https://user-images.githubusercontent.com/10521931/109185627-ce2e5300-7755-11eb-85ea-5b670a762d3f.png">

**Comment by russellgoldenberg** [comment]
mmm that wheel doesn't exist...I'm local and up to date

**Comment by manlikemishap** [comment]
I shrunk both of these generations quite a bit so maybe shouldn't be an issue anymore?

**Comment by russellgoldenberg** [comment]
good enough for now!
