### ISSUE TITLE
resolve byline

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/love-and-ai#15]

**Comment by jadiehm** [comment]
Should we reveal GPT-3 early on in byline? Or leave in vague and fill in later? Or drop GPT-3 since I added in the wayfinding notes? Where should we put credits for Russell and Jan?

**Comment by russellgoldenberg** [comment]
I still think it should be up top. It sets the context. We could sneak a design+code thing somewhere, like top corner or something?

**Comment by manlikemishap** [comment]
If we choose headline that references AI are you fine waiting for reveal? Also very much think you should both be at the top!
