### ISSUE TITLE
stop vs continue for decision outcome

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/love-and-ai#5]

**Comment by jadiehm** [comment]
I added a stop property to the decision outcomes in the doc. Not ever decision needs to retrace its steps, but the ones that do now have stop sign icons under them. Thinking that we can hide the text and lock the scroll if someone chooses one of those and then prompt them to click the stop + text that says something like "Oops, you've chosen a path where the story ends. Click the icon to retrace your steps and explore another path." Then rewind the line and scroll people back to the wheel.

**Comment by jadiehm** [comment]
Probably should hide the stop signs until the decision is active so that we don't tip anyone off.
