### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by manlikemishap** [the-pudding/love-and-ai#54]
Reloaded and scrolled down super quickly. ![image](https://user-images.githubusercontent.com/3290380/109989692-98411f80-7cbd-11eb-81db-50b6eae62eb7.png)

**Comment by russellgoldenberg** [comment]
@manlikemishap  mobile or desktop?

**Comment by manlikemishap** [comment]
desktop, I also had a wonky thing with line before this refresh but did not get a screenshot

**Comment by manlikemishap** [comment]
Did some more experimenting, I think this only happens on desktop refresh?

**Comment by manlikemishap** [comment]
Did some more experimenting, I get the same on mobile w/o refresh and I get it on desktop at refresh

**Comment by manlikemishap** [comment]
line on the side here (guessing you already know about this or it's possibly intended but figured I'd flag)
![image](https://user-images.githubusercontent.com/3290380/110060088-32cf4c00-7d1a-11eb-84aa-7b6e5c93940c.png)
